USE DATABASE DE_PROJECT1;
USE SCHEMA KASI_MART;

-- Load customers.csv into CUSTOMERS
COPY INTO CUSTOMERS
FROM @KASI_MART_STAGE/customers.csv
FILE_FORMAT = KASI_MART_CSV_FORMAT;

-- Load products.csv into PRODUCTS
COPY INTO PRODUCTS
FROM @KASI_MART_STAGE/products.csv
FILE_FORMAT = KASI_MART_CSV_FORMAT;

-- Load orders.csv into ORDERS
COPY INTO ORDERS
FROM @KASI_MART_STAGE/orders.csv
FILE_FORMAT = KASI_MART_CSV_FORMAT;