-- Kasi Mart Data Engineering Project 1
-- Snowflake setup

CREATE DATABASE DE_PROJECT1;

USE DATABASE DE_PROJECT1;

CREATE SCHEMA KASI_MART;

USE SCHEMA KASI_MART;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();
